config/routes.rb
Rails.application.routes.draw do
  get 'dances/new'
  get 'schools/new'
  devise_for :users
  root to: "schools#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :schools do
    resources :school_classes
    get '/dashboard', to: 'school_classes#dashboard'
    resources :teachers
    get '/advancedsearch', to: 'teachers#advancedsearch'
  end
  resources :dances
end

app/controllers/school_classes_controller.rb
class SchoolClassesController < ApplicationController
  before_action :set_school, only: %i[index new create destroy dashboard]

  def index
    @schoolclasses = SchoolClass.where(school_id: @school.id).order(:room_number).order(:beginning_of_time).order(:day_of_week)
  end

  def dashboard
    @schoolclasses = SchoolClass.where(school_id: @school.id).order(:room_number).order(:beginning_of_time).order(:day_of_week)
    roomnumber_arr = []
    @schoolclasses.each do |roomschool|
      roomnumber_arr << roomschool.room_number
    end
    @room = roomnumber_arr.uniq
    @roomcount = @room.count - 1

    #ajouter une boucle for or for each pour avoir n room pour n horaires etc...
    for w in 0..@roomcount

      x = 1
      for n in 0..@roomcount
        instance_variable_set("@day_arr_#{x}", [])
        instance_variable_set("@begin_arr_#{x}", [])
        instance_variable_set("@end_arr_#{x}", [])
        x += 1
      end

      #a supprimer a la fin de l'indus
      day_arr_1 = []
      begin_arr_1 = []
      end_arr_1 = []


      day_arr = []
      begin_arr = []
      begin_time = []
      end_arr = []
      schoolday = []
      @schoolclasses.each do |schoolclass|
        if schoolclass.room_number == @room[w]
          day_arr << schoolclass.day_of_week
          begin_arr << schoolclass.beginning_of_time.strftime("%H:%M")
          end_arr << schoolclass.end_of_time.strftime("%H:%M")
        end
      end

      v = 1
      instance_variable_set("@schoolday_#{v}", day_arr.uniq)
      instance_variable_set("@begintime_#{v}", begin_arr.uniq)
      begin_time = begin_arr.uniq
      schoolday = day_arr.uniq
      @endtime = end_arr[-1]

      #pour tester les réusltats
      @schoolclasses.each do |schoolclass|
        if schoolclass.room_number == @room[w]
          day_arr_1 << schoolclass.day_of_week
          begin_arr_1 << schoolclass.beginning_of_time.strftime("%H:%M")
          end_arr_1 << schoolclass.end_of_time.strftime("%H:%M")
        end
      end

      @endtime_t = end_arr_1[-1]
      @schoolday_t = day_arr_1.uniq
      @begintime_t = begin_arr_1.uniq
      #fin test resultat

      arr_cours_h1 = []
      arr_cours_h2 = []
      arr_cours_h3 = []
      arr_cours_h4 = []


      @countbegintime = begin_time.count - 1
      @countclass = @schoolclasses.count - 1

      for countbegintime in 0..@countbegintime
        for countclass in 0..@countclass
          time_condition = @schoolclasses[countclass].beginning_of_time.strftime("%H:%M").include?(begin_time[countbegintime])

          if time_condition
            # Use an array to store the result instead of creating individual variables
            arr_cours_h = SchoolClass.where(school_id: @school.id).where(beginning_of_time: begin_time[countbegintime]).where(room_number: @room[w]).order(:day_of_week)
            instance_variable_set("@arr_cours_h#{countbegintime}", arr_cours_h)
          end
        end
      end

      #test resultat
      @schoolclasses.each do |schoolclass|
        if ( schoolclass.beginning_of_time.strftime("%H:%M").include?(@begintime_1[0]) && schoolclass.room_number == @room[w])
          arr_cours_h1 << schoolclass
        elsif(schoolclass.beginning_of_time.strftime("%H:%M") == @begintime_1[1] && schoolclass.room_number == @room[w])
          arr_cours_h2 << schoolclass
        elsif(schoolclass.beginning_of_time.strftime("%H:%M") == @begintime_1[2] && schoolclass.room_number == @room[w])
          arr_cours_h3 << schoolclass
        elsif(schoolclass.beginning_of_time.strftime("%H:%M") == @begintime_1[3] && schoolclass.room_number == @room[w])
          arr_cours_h4 << schoolclass
        end
      end
      #fin test resultat

      classdance1 = [arr_cours_h1, arr_cours_h2, arr_cours_h3, arr_cours_h4]
      @countbegintime = begin_time.count - 1
      classdance = []

      for countbegintime in 0..@countbegintime
        classdance << instance_variable_get("@arr_cours_h#{countbegintime}")
        # Use instance_variable_get to get the value of the instance variable
      end


      # for countarray in 0..@countarray
      #   for countday in 0..@countday do
      #     if(classdance1[countarray][countday] == nil)
      #       classdance1[countarray].insert(countday, "")
      #     elsif(classdance1[countarray][countday].day_of_week != schoolday[countday])
      #       classdance1[countarray].insert(countday, "")
      #     end
      #   end
      # end



      x = 1
      # ajoute l'horaire pour chaque element
      for countarray in 0..@countarray
        instance_variable_set("@cours_h#{x}", classdance[countarray].to_a.insert(0, begin_time[countarray]))
        x += 1
      end
      t = 1
      instance_variable_set("@v", instance_variable_get("@cours_h#{t}").count - 1)
      danceclass = []
      m = 1
      for countarray in 0..@countarray
        danceclass << instance_variable_get("@cours_h#{m}")
        # Use instance_variable_get to get the value of the instance variable
        m += 1
      end


      @danceclass = danceclass
      @danceclasscount = danceclass.count - 1

      @countday = day_arr.uniq.count
      @countarray = classdance.count - 1

      for countarray in 0..@countarray
        for countday in 1..@countday
          current_element = @danceclass[countarray][countday]

          if current_element.nil? || current_element.day_of_week != schoolday[countday]
            #modifier cette ligne de code pour inserer les elements vide
            @danceclass[countarray].insert(countday,"")

          end
        end
      end

    end
  end

  def new
    @schoolclass = SchoolClass.new
    @school = School.find(params[:school_id])
    set_arg_creation
  end

  def create
    set_arg_creation

    @schoolclass = SchoolClass.new(schoolclass_params)
    @schoolclass.school = @school
    @schoolclassesroom = SchoolClass.where(beginning_of_time: @schoolclass.beginning_of_time, end_of_time: @schoolclass.end_of_time, room_number: @schoolclass.room_number, day_of_week: @schoolclass.day_of_week, school_id: @schoolclass.school_id)
    @schoolclassestea = SchoolClass.where(beginning_of_time: @schoolclass.beginning_of_time, end_of_time: @schoolclass.end_of_time, teacher_name: @schoolclass.teacher_name, day_of_week: @schoolclass.day_of_week)

    if @schoolclassestea.any?
      redirect_to new_school_school_class_path(:school_id => @school.id) ,notice: "#{@schoolclass.teacher_name} est déja pris à cette horaire"
    elsif @schoolclassesroom.any?
      redirect_to new_school_school_class_path(:school_id => @school.id) ,notice: "La salle est déja réservé à cette horaire dans cette école"
    elsif @schoolclass.save
      redirect_to schools_path, notice: "Votre cours a bien été crée"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @schoolclass = SchoolClass.find(params[:id])
    @schoolclass.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to school_school_classes_path(:school_id => @school.id), status: :see_other
  end

  private

  def schoolclass_params
    params.require(:school_class).permit(:type_of_dance, :level, :end_of_time, :beginning_of_time, :day_of_week, :teacher_name, :room_number)
  end

  def set_school
    @school = School.find(params[:school_id])
  end

  def set_arg_creation
    @nameschool = School.where(id: @school.id, school_id: @school.school_id)
    if @school.school_id != nil
      school = @school.school_id
    elsif @school.school_id == nil
      school = @school.id
    end
    @teacherstoselect = Teacher.joins("INNER JOIN school_teachers ON school_teachers.teacher_id = teachers.id INNER JOIN schools ON schools.id = school_teachers.school_id where schools.id = #{school} or schools.school_id = #{school} ")
    #nombre de room
    x = @school.number_room
    arrtess = []#pour stocker les valeurs que je souhaite
    arrtess << x
    while x > 1
      x -= 1
      arrtess << x
    end
    @countarr = arrtess
  end
end

app/views/school_classes/_form.html.erb
<h1>Schools#new</h1>


<div class="">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <%= simple_form_for [@school, @schoolclass] do |f| %>
        <div class="row">
          <div class="col-8">Choisisez votre type de dance:
            <%= f.collection_select :type_of_dance, Dance.all, :fullname, :fullname,prompt: true %>
          </div>
          <div class="col-8">Choisisez votre niveau:
            <%= f.select :level,  options_for_select(%w[ Débutant Inter1 Inter2 Inter/Conf Confirmé]),prompt: true %>
          </div>
          <div class="col-8">
            <%= f.input :beginning_of_time %>
          </div>
          <div class="col-8">
            <%= f.input :end_of_time %>
          </div>
          <div class="col-8">Choisisez le jour de votre cours:
            <%= f.select :day_of_week , options_for_select(%w[Dimanche Lundi Mardi Mercredi Jeudi Vendredi Samedi]),prompt: true %>
          </div>
          <div  class="col-8">Choisisez votre Professeur de dance:
            <%= f.collection_select :teacher_name, @teacherstoselect,->(p){ "#{p.first_name} #{p.last_name}" },->(p){ "#{p.first_name} #{p.last_name}" },prompt: true %>
          </div>
          <div  class="col-8">Choisisez votre Piece:
            <%= f.collection_select :room_number, @countarr, :to_s, :to_s,prompt: true %>
          </div>
            <%= f.submit  class: "btn btn-super"%>
      <% end %>


    </div>
  </div>
</div>

app/views/school_classes/dashboard.html.erb
<h1>Mon dashboard</h1>
<!-- app/views/restaurants/index.html.erb -->
<%= link_to "Acceder au listing des ecoles", root_path %>
<% for u in 0..@roomcount  %>

<% if @room.include?(@room[u]) %>
  <table border="1px solid black">
    <tr>
      <th>&nbsp;</th>
      <% @schoolday_1.each do |schoolday| %>
        <th><%= schoolday %></th>
      <% end %>
    </tr>
    <tr >
    <% for i in 0..@danceclasscount  %>
      <td><%= @danceclass[i][0] %></td>
      <% for t in 1..@v  %>
        <% if @danceclass[i][t] == "" %>
          <td>&nbsp;</td>
        <% else %>
          <td><%= @danceclass[i][t].level %><p><%= @danceclass[i][t].teacher_name %><p><%= @danceclass[i][t].type_of_dance %><p><%= @danceclass[i][t].day_of_week %><p><%= @danceclass[i][t].room_number %></td>
        <% end %>
      <% end  %>
    </tr>
    <% end %>
  <tr>
    <td><%= @endtime %></td>
  </tr>
  </table>
<% end %>
<% end %>

app/views/school_classes/edit.html.erb
<%= render "form", schoolclass: @schoolclass %>

app/views/school_classes/index.html.erb
<!-- app/views/restaurants/index.html.erb -->
<h1>Mes cours:</h1>
<%= link_to "Acceder au listing des ecoles", root_path %>
<ul>
  <% @schoolclasses.each do |schoolclass| %>
    <li>Nom du professeur: <%=  schoolclass.teacher_name %></li>
    <li>Jour de la semaine: <%=  schoolclass.day_of_week %></li>
    <li>Type de dance: <%=  schoolclass.type_of_dance %></li>
    <li>Niveau: <%=  schoolclass.level %></li>
    <li><%= schoolclass.beginning_of_time.strftime("Heure de début: %H:%M:%S") %></li>
    <li><%= schoolclass.end_of_time.strftime("Heure de fin: %H:%M:%S") %></li>
    <%= link_to "Supprimer cette horaire de mon école", school_school_class_path(@school,schoolclass), data: {turbo_method: :delete, turbo_confirm: "Etes-vous sure de vouloir supprimer cette horaire?"}  %>
    <p></p>
  <% end %>
</ul>

app/views/school_classes/new.html.erb
<h1>Schools#new</h1>


<div class="">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <%= simple_form_for [@school, @schoolclass] do |f| %>
        <div class="row">
        <div class="col-8">
            <%= f.input :school_name %>
          </div>
          <div class="col-8">Choisisez votre type de dance:
            <%= f.collection_select :type_of_dance, Dance.all, :fullname, :fullname,prompt: true %>
          </div>
          <div class="col-8">Choisisez votre niveau:
            <%= f.select :level,  options_for_select(%w[ Débutant Inter1 Inter2 Inter/Conf Confirmé]) %>
          </div>
          <div class="col-8">
            <%= f.input :beginning_of_time %>
          </div>
          <div class="col-8">
            <%= f.input :end_of_time %>
          </div>
          
          <div class="col-8">Choisisez le jour de votre cours:
            <%= f.select :day_of_week , options_for_select(%w[Dimanche Lundi Mardi Mercredi Jeudi Vendredi Samedi]) %>
          </div>
          <div class="col-8">
            <%= f.input :room_number %>
          </div>
          <div  class="col-8">Choisisez votre Professeur de dance:
            <%= f.collection_select :teacher_name, Teacher.all,->(p){ "#{p.first_name} #{p.last_name}" },->(p){ "#{p.first_name} #{p.last_name}" },prompt: true %>
          </div>
          
          
            <%= f.submit  class: "btn btn-super"%>
      <% end %>
      
      
    </div>
  </div>
</div>

app/views/school_classes/temp.html.erb
<% @schoolday_1.each do |dayschool| %>
          <% @schoolclasses.each do |schoolclasses| %>
            <% if schoolclasses.room_number == 1 && schoolclasses.beginning_of_time.strftime("%H:%M").include?(@begintime_1[0]) && begintime.include?(@begintime_1[0]) && schoolclasses.day_of_week.include?(dayschool) %>
              <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level %><p> <%= schoolclasses.type_of_dance %> <%= schoolclasses.day_of_week %></td>
            <% elsif schoolclasses.room_number == 1 && schoolclasses.beginning_of_time.strftime("%H:%M").include?(@begintime_1[1]) && begintime.include?(@begintime_1[1]) && schoolclasses.day_of_week.include?(dayschool) %>
              <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level %><p> <%= schoolclasses.type_of_dance %> <%= schoolclasses.day_of_week %></td>
            <% elsif schoolclasses.room_number == 1 && schoolclasses.beginning_of_time.strftime("%H:%M").include?(@begintime_1[2]) && begintime.include?(@begintime_1[2]) && schoolclasses.day_of_week.include?(dayschool) %>
              <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level %><p> <%= schoolclasses.type_of_dance %> <%= schoolclasses.day_of_week %></td>
            <% elsif schoolclasses.room_number == 1 && schoolclasses.beginning_of_time.strftime("%H:%M").include?(@begintime_1[3]) && begintime.include?(@begintime_1[3]) && schoolclasses.day_of_week.include?(dayschool) %>
              <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level %><p> <%= schoolclasses.type_of_dance %> <%= schoolclasses.day_of_week %></td>
            <% end %>
          <% end %>
        <% end %>




                <!-- @cours_h1-->
        <!--<% @schoolday_1.each do |dayschool| %>
          <% @schoolclasses.each do |schoolclasses| %>
            <% if schoolclasses.room_number == 1 && schoolclasses.beginning_of_time.strftime("%H:%M").include?(@begintime_1[0]) && begintime.include?(@begintime_1[0]) && schoolclasses.day_of_week.include?(dayschool) %>
              <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level %><p> <%= schoolclasses.type_of_dance %> <%= schoolclasses.day_of_week %></td>
            <% elsif schoolclasses.room_number == 1 && schoolclasses.beginning_of_time.strftime("%H:%M").include?(@begintime_1[1]) && begintime.include?(@begintime_1[1]) && schoolclasses.day_of_week.include?(dayschool) %>
              <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level %><p> <%= schoolclasses.type_of_dance %> <%= schoolclasses.day_of_week %></td>
            <% elsif schoolclasses.room_number == 1 && schoolclasses.beginning_of_time.strftime("%H:%M").include?(@begintime_1[2]) && begintime.include?(@begintime_1[2]) && schoolclasses.day_of_week.include?(dayschool) %>
              <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level %><p> <%= schoolclasses.type_of_dance %> <%= schoolclasses.day_of_week %></td>
            <% elsif schoolclasses.room_number == 1 && schoolclasses.beginning_of_time.strftime("%H:%M").include?(@begintime_1[3]) && begintime.include?(@begintime_1[3]) && schoolclasses.day_of_week.include?(dayschool) %>
              <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level %><p> <%= schoolclasses.type_of_dance %> <%= schoolclasses.day_of_week %></td>
            <% end %>
          <% end %>
        <% end %>-->

        <!--
<table>
  <tr>
   <th>&nbsp;</th>
    <% if @room.include?(2)  %>
      <% @schoolday_2.each do |schoolday| %>
        <th><%= schoolday %></th>
      <% end %>
    <% end %>
  </tr>
  <% @begintime_2.each do  | begintime | %>
    <tr>
    <td><%= begintime %></td>
    <% @schoolclasses.each do |schoolclasses|  %>
          <% if schoolclasses.room_number == 2 %>
            <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level  %><p> <%= schoolclasses.type_of_dance  %> <%= schoolclasses.room_number  %></td>
          <% end  %>
    <% end  %>
    </tr>
  <% end %>
</table>
<table>
  <tr>
   <th>&nbsp;</th>
    <% if @room.include?(3)  %>
      <% @schoolday_3.each do |schoolday| %>
        <th><%= schoolday %></th>
      <% end %>
    <% end %>
  </tr>
  <% @begintime_3.each do  | begintime | %>
    <tr>
    <td><%= begintime %></td>
    <% @schoolclasses.each do |schoolclasses|  %>
          <% if schoolclasses.room_number == 3 %>
            <td><%= schoolclasses.teacher_name %><p><%= schoolclasses.level  %><p> <%= schoolclasses.type_of_dance  %> <%= schoolclasses.room_number  %></td>
          <% end  %>
    <% end  %>
    </tr>
  <% end %>
</table> -->

for countbegintime in 0..@countbegintime
  for countclass in 0..@countclass
    time_condition = @schoolclasses[countclass].beginning_of_time.strftime("%H:%M").include?(@begintime_1[countbegintime])

    if time_condition
      # Use an array to store the result instead of creating individual variables
      arr_cours_h = SchoolClass.where(school_id: @school.id).where(beginning_of_time: @begintime_1[countbegintime])
      instance_variable_set("@arr_cours_h#{countbegintime}", arr_cours_h)
    end
  end
end

User
@countbegintime = @begintime_1.count - 1
@countclass = @schoolclasses.count - 1

for countbegintime in 0..@countbegintime
  for countclass in 0..@countclass
    time_condition = @schoolclasses[countclass].beginning_of_time.strftime("%H:%M").include?(@begintime_1[countbegintime])

    if time_condition
    # Initialize an array to store the results
    @arr_cours_h"#{countbegintime}" = []
      # Add the result to the array
      @arr_cours_h"#{countbegintime}" << SchoolClass.where(beginning_of_time: @begintime_1[countbegintime])
    end
  end
end




<!-- <tr >
        <td><%= @cours_h1[0] %></td>
        <% for t in 1..@v  %>
          <td><%= @cours_h1[t].level %><p><%= @cours_h1[t].teacher_name %><p><%= @cours_h1[t].type_of_dance %><p><%= @cours_h1[t].day_of_week %></td>
        <% end  %>
      </tr>
      <tr >
        <td><%= @cours_h2[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h2[t] == "" %>
            <td>&nbsp;</td>
          <% else %>

            <td><%= @cours_h2[t].level %><p><%= @cours_h2[t].teacher_name %><p><%= @cours_h2[t].type_of_dance %><p><%= @cours_h2[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>
      <tr >
        <td><%= @cours_h3[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h3[t] == "" %>
            <td>&nbsp;</td>
          <% else %>

            <td><%= @cours_h3[t].level %><p><%= @cours_h3[t].teacher_name %><p><%= @cours_h3[t].type_of_dance %><p><%= @cours_h3[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>
      <tr >
        <td><%= @cours_h4[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h4[t] == "" %>
            <td>&nbsp;</td>
          <% else %>
            <td><%= @cours_h4[t].level %><p><%= @cours_h4[t].teacher_name %><p><%= @cours_h4[t].type_of_dance %><p><%= @cours_h4[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>-->


<tr >
        <td><%= @cours_h2[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h2[t] == "" %>
            <td>&nbsp;</td>
          <% else %>

            <td><%= @cours_h2[t].level %><p><%= @cours_h2[t].teacher_name %><p><%= @cours_h2[t].type_of_dance %><p><%= @cours_h2[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>
      <tr >
        <td><%= @cours_h3[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h3[t] == "" %>
            <td>&nbsp;</td>
          <% else %>

            <td><%= @cours_h3[t].level %><p><%= @cours_h3[t].teacher_name %><p><%= @cours_h3[t].type_of_dance %><p><%= @cours_h3[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>
      <tr >
        <td><%= @cours_h4[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h4[t] == "" %>
            <td>&nbsp;</td>
          <% else %>
            <td><%= @cours_h4[t].level %><p><%= @cours_h4[t].teacher_name %><p><%= @cours_h4[t].type_of_dance %><p><%= @cours_h4[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>




            <tr >
        <td><%= @cours_h2[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h2[t] == "" %>
            <td>&nbsp;</td>
          <% else %>

            <td><%= @cours_h2[t].level %><p><%= @cours_h2[t].teacher_name %><p><%= @cours_h2[t].type_of_dance %><p><%= @cours_h2[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>
      <tr >
        <td><%= @cours_h3[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h3[t] == "" %>
            <td>&nbsp;</td>
          <% else %>

            <td><%= @cours_h3[t].level %><p><%= @cours_h3[t].teacher_name %><p><%= @cours_h3[t].type_of_dance %><p><%= @cours_h3[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>
      <tr >
        <td><%= @cours_h4[0] %></td>
        <% for t in 1..@v  %>
          <% if @cours_h4[t] == "" %>
            <td>&nbsp;</td>
          <% else %>
            <td><%= @cours_h4[t].level %><p><%= @cours_h4[t].teacher_name %><p><%= @cours_h4[t].type_of_dance %><p><%= @cours_h4[t].day_of_week %></td>
          <% end %>
        <% end  %>
      </tr>