config/routes.rb
Rails.application.routes.draw do
  get 'dances/new'
  get 'schools/new'
  devise_for :users
  root to: "schools#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :schools do
    resources :school_classes
    get '/dashboard', to: 'school_classes#dashboard'
    resources :teachers
    get '/advancedsearch', to: 'teachers#advancedsearch'
  end
  resources :dances
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_dances, dependent: :destroy
  has_many :dances, through: :teacher_dances, dependent: :destroy
  has_many :school_teachers, dependent: :destroy
  has_many :schools, through: :school_teachers

  VALID_EMAIL_REGEX = /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
  validates :first_name, :last_name, :date_of_birth,:dance_ids, presence: true
  validates :address_mail, presence: true, format: { with: VALID_EMAIL_REGEX, multiline: true }
  #uniqueness:{case_sensetive:false},
  validates :phone_number, presence: true, length: { minimum: 10 }
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy, :test]

  def index
    @school = School.find(params[:school_id])
    if @school.school_id != nil
      school = @school.school_id
    elsif @school.school_id == nil
      school = @school.id
    end
    @teachers = Teacher.joins("INNER JOIN school_teachers ON school_teachers.teacher_id = teachers.id INNER JOIN schools ON schools.id = school_teachers.school_id where schools.id = '#{school}' or schools.school_id = '#{school}' ")
  end

  def new
    @school = School.find(params[:school_id])
    @teacher = Teacher.new
    @dances = Dance.all
  end

  def create
    @school = School.find(params[:school_id])
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      @schoolteacher = SchoolTeacher.new(school_id:@school.id, teacher_id: @teacher.id)
      @schoolteacher.save
      redirect_to school_teachers_path, notice: "Vous avez bien crée le professeur: #{@teacher.first_name} #{@teacher.last_name}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @school = School.find(params[:school_id])
  end

  def edit
    @school = School.find(params[:school_id])
  end

  def update
    @school = School.find(params[:school_id])
    @teacher.update(teacher_params)
    redirect_to school_teacher_path(@school,@teacher), notice: "Vous avez bien mis à jour le professeur: #{@teacher.first_name} #{@teacher.last_name}"
  end

  def destroy
    @school = School.find(params[:school_id])
    @teacher = Teacher.find(params[:id])
    @idtocatch = School.where("id= '#{@school.id}'or school_id='#{@school.id}'")
    idschooltodelete = []
    @idtocatch.each do |idto|
      idschooltodelete << idto.id
    end
    idschooltodelete.each do |schooltodelete|
      teachertodelete = @teacher.id
      @idtodelete = SchoolTeacher.where(:teacher_id => teachertodelete, :school_id => schooltodelete)
      idto = []
      @idtodelete.each do |idtodelete|
        idto << idtodelete.id
      end
      SchoolTeacher.delete(idto)
    end
    redirect_to school_teachers_path(@school), status: :see_other,notice: "Vous venez de supprimer ce #{@teacher.first_name} #{@teacher.last_name} de votre école"
  end

  def advancedsearch
    @school = School.find(params[:school_id])
    @teachers = Teacher.all.order(params[:sort])
  end

  private

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :date_of_birth, :phone_number, :address_mail, dance_ids:[])
  end

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end
end

app/views/teachers/_form.html.erb
<h1>Teachers#new</h1>
<p>Find me in app/views/teachers/edit.html.erb</p>

<div class="">
  <div class="row justify-content-center" >
    <div class="col-12 col-lg-6">
      <%= simple_form_for [@school, @teacher] do |f| %>
        <div class="row">
          <div class="col-8">
            <%= f.input :first_name %>
          </div>
          <div class="col-8">
            <%= f.input :last_name %>
          </div>
          <%= f.input :date_of_birth,
            as: :string,
            input_html: { data: { controller: "datepicker"} } %>
          <div class="col-8">
            <%= f.input :phone_number %>
          </div>
          <div class="col-8">
            <%= f.input :address_mail %>
          </div>
          <div>Si vous ne trouvez pas le type dance que vous cherchez, cliquez sur le lien suivant:</div>
          <%= link_to "Ajouter un nouveau type de dance", new_dance_path %>
          <div class="col-8" >
            <%= f.association :dances,
                             as: :check_boxes,
                             label_method: :fullname,
                             :label => "Choisissez vos spécialités:" %>
          </div>
          <%= f.submit class: "btn btn-super"%>
      <% end %>
    </div>
  </div>
</div>

app/views/teachers/advancedsearch.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <h1>Teachers List</h1><table>
  <tr>
    <th><%= link_to "Nom du Professeur", :sort => "first_name" %></th>
    <th><%= link_to "Prenom du professeur", :sort => "last_name" %></th>
    <th><%= link_to "Date d'anniversaire", :sort => "date_of_birth" %> </th>
  </tr>
 <% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.first_name %></td>
    <td><%=teacher.last_name %></td><td>
    <td><%=teacher.date_of_birth %></td>
    <td><%=teacher.phone_number %></td>
    <td><%=teacher.address_mail %></td>
  </tr>
  <% end %>
 </table>
  </div>
</div>

app/views/teachers/edit.html.erb
<%= render "form", teacher: @teacher %>

app/views/teachers/index.html.erb
<h1>Tous mes profs</h1>
<ul>
  <% @teachers.each do |teacher| %>
  <li><%= link_to teacher.first_name, school_teacher_path(:id => teacher.id) %></li>
  <% end %>
</ul>

<% if @school.school_id == nil  %>
  <%= link_to "Créer un nouveau prof pour l'ecole", new_school_teacher_path %>
<% end  %>
<%= link_to "Acceder au listing des ecoles", root_path %>
<%= link_to "Chercher un nouveau professeur pour mon ecole", school_advancedsearch_path %>

app/views/teachers/new.html.erb
<h1>Teachers#new</h1>
<p>Find me in app/views/teachers/new.html.erb</p>

<div class="">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <%= simple_form_for(@teacher) do |f| %>
        <div class="row">
          <div class="col-8">
            <%= f.input :first_name %>
          </div>
          <div class="col-8">
            <%= f.input :last_name %>
          </div>
          <div class="col-8">
            <%= f.input :date_of_birth %>
          </div>
          <div class="col-8">
            <%= f.input :phone_number %>
          </div>
          <div class="col-8">
            <%= f.input :address_mail %>
          </div>
          <div class="col-8">
            <%= f.collection_check_boxes(:specialty, Dance.all,:fullname,:fullname,checked: true) %>
          </div>
          <%= f.submit  class: "btn btn-super"%>
      <% end %>
    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<h2><%= @teacher.first_name %></h2>
<p><%= @teacher.last_name %></p>
<p><%= @teacher.date_of_birth %></p>
<p><%= @teacher.phone_number %></p>
<p><%= @teacher.address_mail %></p>
<p><% @teacher.dances.each do |dance| %></p>
<p><%= dance.fullname %></p>
<p><% end %></p>
<%= link_to "Retour à l'index des profs", school_teachers_path %>
<% if @school.school_id == nil  %>
  <%= link_to "Mettre à jour ce professeur",edit_school_teacher_path(@school,@teacher) %>
  <%= link_to "Supprimer ce professeur de mon école", school_teacher_path(@school,@teacher), data: {turbo_method: :delete, turbo_confirm: "Are you sure"}  %>
<% end  %>