config/routes.rb
Rails.application.routes.draw do
  get 'dances/new'
  get 'schools/new'
  devise_for :users
  root to: "schools#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :schools do
    resources :school_classes
    get '/dashboard', to: 'school_classes#dashboard'
    resources :teachers
    get '/advancedsearch', to: 'teachers#advancedsearch'
  end
  resources :dances
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :school, optional: true
  has_many :user_schools
  has_many :users, through: :user_schools
  has_many :school_classes
  has_many :school_teachers, dependent: :destroy
  has_many :teachers, through: :school_teachers

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  VALID_EMAIL_REGEX= /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  validates :name,:address,:type_of_structure,:approval_number,:phone_number,:address_mail_pdt,:phone_number_pdt,:number_room, presence: true
  validates :number_room, numericality: { only_integer: true,greater_than_or_equal_to: 1 }
  validates :address_mail_pdt , presence: true,format:{with:VALID_EMAIL_REGEX,multiline:true}
  #uniqueness:{case_sensetive:false},
  validates :phone_number,:phone_number_pdt, length: { minimum: 10 }
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def new
    @school = School.new
  end

  def create
    school_id = params[:school_id]
    @school = School.new(school_params)

    if @school.save
      @userschool = UserSchool.new(school_id:@school.id, user_id: current_user.id)
      @userschool.save
      redirect_to schools_path, notice: "Votre école a bien été crée: #{@school.name}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

def school_params
  params.require(:school).permit(:name, :address, :approval_number, :phone_number, :address_mail_pdt, :phone_number_pdt,:type_of_structure,:number_room,:school_id)
end

end

app/views/schools/_form.html.erb
<h1>Schools#new</h1>


<div class="">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <%= simple_form_for(@school) do |f| %>
        <div class="row">
          <div class="col-8">
            <%= f.input :name %>
          </div>
          <div class="col-8">
            <%= f.input :address,
              input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
              wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
            %>
          </div>
          <div class="col-8">
            <%= f.select :type_of_structure,  options_for_select(%w[ Société Association]) %>
          </div>
          <div class="col-8">
            <%= f.input :approval_number %>
          </div>
          <div class="col-8">
            <%= f.input :phone_number %>
          </div>
          <div class="col-8">
            <%= f.input :address_mail_pdt %>
          </div>
          <div class="col-8">
            <%= f.input :phone_number_pdt %>
          </div>
          <div class="col-8">
            <%=  f.hidden_field :school_id,  :value => params[:school_id] %>
          </div>
          <div class="col-8">
            <%= f.input :number_room %>
          </div>
                <%= f.submit  class: "btn btn-super"%>
      <% end %>
    </div>
  </div>
</div>

app/views/schools/edit.html.erb
<%= render "form", school: @school %>

app/views/schools/index.html.erb
<% if current_user.schools.any? %>
  <ul>
    <% current_user.schools.each do |school| %>
        <li><%= school.name %></li>
        <li><%= school.id %></li>
      <% if school.school_id == nil %>
        <%= link_to "Créer vos sites supplémentaires", schools_new_path(:school_id => school.id) %>
      <% end  %>
        <%= link_to "Créer vos planning", new_school_school_class_path(:school_id => school.id) %>
        <%= link_to "Acceder au listing des professeurs", school_teachers_path(:school_id => school.id) %>
        <%= link_to "Ajouter un nouveau type de danse", new_dance_path %>
        <%= link_to "Accéder au cours que vous avez créer", school_school_classes_path(:school_id => school.id) %>
        <%= link_to "Accéder à votre dashboard", school_dashboard_path(:school_id => school.id) %>
    <% end %>
  </ul>
<% else %>
  <%= link_to "Créer votre école", schools_new_path %>
<% end  %>

app/views/schools/new.html.erb
<h1>Schools#new</h1>


<div class="">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <%= simple_form_for(@school) do |f| %>
        <div class="row">
          <div class="col-8">
            <%= f.input :name %>
          </div>
          <div class="col-8">
            <%= f.input :address %>
          </div>
          <div class="col-8">
            <%= f.select :type_of_structure,  options_for_select(%w[ Société Association]) %>
          </div>
          <div class="col-8">
            <%= f.input :approval_number %>
          </div>
          <div class="col-8">
            <%= f.input :phone_number %>
          </div>
          <div class="col-8">
            <%= f.input :address_mail_pdt %>
          </div>
          <div class="col-8">
            <%= f.input :phone_number_pdt %>
          </div>
          <div class="col-8">
            <%=  f.hidden_field :school_id,  :value => params[:school_id] %>
          </div>
                <%= f.submit  class: "btn btn-super"%>
      <% end %>
    </div>
  </div>
</div>